### ISSUE TITLE
Migrate scraper and database to the cloud?

### ISSUE THREAD

**Issue by radumas** [CivicTechTO/ttc_subway_times#10]
The scraper isn't necessarily the fastest on the Pi. And there is certainly a limit to the amount of data that can be stored on the SD card. 

If I get a few hours I could set up my old desktop as a server. Otherwise open to suggestions for cheap hosting options.

**Comment by samkodes** [comment]
Amazon EC2 was suggested -- free 12month trial with a new AWS account.

**Comment by radumas** [comment]
[Scraping Hub](https://scrapinghub.com/scrapy-cloud/) Would offer free hosting for the scraper (coded in scrapy) data is only retained for 7 days in the free version.
[Heroku](https://www.heroku.com/pricing) would offer free hosting of the scraper. The free tier of PostgreSQL has a max of 10k rows. 
AWS Relational Database Service (RDS) Offers an always on Micro instance of PostgreSQL with 20GB of data for free for 12 months so... let's go with that.

**Comment by radumas** [comment]
We're on AWS!
