### ISSUE TITLE
Record poll number in database

### ISSUE THREAD

**Issue by samkodes** [CivicTechTO/ttc_subway_times#3]
It would be helpful in algorithm design to be able to treat each cycle through the stations as a single "poll" of the entire system.
I propose assigning each poll a unique sequential number, similar to requestid. 
This number could be stored in the requests table and be used to pull together all requests from a single poll.

**Comment by samkodes** [comment]
After looking at the first data set, it appears that "polls" tend to be generally quite incomplete. This makes this idea of treating polls as coherent objects less appealing. It might be better to make the scraper try harder to get complete polls than one that hurries up to try again.

**Comment by radumas** [comment]
Since each run of the scraper starts every minute, one can get a unique run by truncating the create_date timestamp to the minute. 
@samkodes Any sense if there's any pattern to the other missing values?

**Comment by samkodes** [comment]
I'll try that create_date trick for now, but I poll_id would be more reliable in the long term. 
I see between 175 and 233 requests per station in the first data set. Ideally there should be the same number of requests stored per station. 
![requestsperstation](https://cloud.githubusercontent.com/assets/25047538/22850548/38d0ae96-efd9-11e6-8457-7b637bdcaacd.png)

**Comment by samkodes** [comment]
Oh, downward trend because scraper dies on request failure?

**Comment by radumas** [comment]
>Oh, downward trend because scraper dies on request failure? Or would that be a lot smoother / monotonic?
It shouldn't, the absence of data is being caught and logged. 
>Are you just running the script as a cron task, or is the looping done in python?
Cron
>Don't know if apparent downward trend means poll runs out of time?
AFAIK Cron doesn't kill a process because it "runs out of time"

**Comment by samkodes** [comment]
fyi, create_date trick doesn't really work - offsets or lags throw everything off.
![reqs_per_poll_day1](https://cloud.githubusercontent.com/assets/25047538/22850882/5e625806-efe0-11e6-8f9d-5e94d1399bbf.png)

**Comment by radumas** [comment]
Yeah, I discovered after that each run of the scraper is probably not finishing in a minute...

**Comment by samkodes** [comment]
See psychedelic dot picture in issue #5

**Comment by radumas** [comment]
Fixed by #12
