### ISSUE TITLE
Include the York University Extension stations

### ISSUE THREAD

**Issue by radumas** [CivicTechTO/ttc_subway_times#35]
There are new stations! We should have their data.

Also, Line 1 stations were numbered 1-32, what are these new stations' ids?

**Comment by rihabr** [comment]
These are the new IDs - thankfully they start at 70 and don't overwrite the old ones:

![image](https://user-images.githubusercontent.com/6369268/46249897-ebcd2600-c3fe-11e8-875e-ddf22f55ee84.png)

**Comment by radumas** [comment]
Thanks @rihabr! So we'd need to add those 6 stations the scraper.
