### ISSUE TITLE
Improve request processing time

### ISSUE THREAD

**Issue by radumas** [CivicTechTO/ttc_subway_times#5]
This may just be my Pi struggling a little, but according to the 2 hr data sample the average request (and bear in mind that `create_date` is truncated to the second), completion time of each station request is, on average 2.6 secs with a median of 2s (truncated). There are 68 stations, so each run is taking longer than the run frequency (I think).

Could investigate using a different requests library to try to have non-blocking IO. [example](http://stackoverflow.com/a/32238131/4047679)

Or, bundle inserts, which should reduce lost time from creating connections to the database.

**Comment by samkodes** [comment]
Here's a picture of what the first day's requests / responses look like.
The tilt as you go up is the lag as we move through the loop. Empty spots are missing dots.
We're still sampling each station every 60s or so, except for gaps and a couple swerves.
My take: this is not a big problem, and OS-level parallelism is all that's needed given the current run-by-cron design. 

![first_day_requests](https://cloud.githubusercontent.com/assets/25047538/22851039/d5451e78-efe4-11e6-9e42-210b11100816.png)

**Comment by samkodes** [comment]
Second thought: the streams may be crossed in a few places. DO NOT CROSS THE STREAMS

**Comment by samkodes** [comment]
Note also the occasional weird backwards swerves on the Shepherd line (top 4 stations in the picture - 64-67); this proves that create_date (a time returned by the API) is in general not the same as the time of the request, and may explain the forward swerves elsewhere.

**Comment by samkodes** [comment]
Ok, I did it -- a first stab at nonblocking IO for web requests works, and it runs superfast - 4s for an entire poll --- definitely the way to go!

**Comment by radumas** [comment]
Fixed by #12
